#!/bin/bash

REPO_URL=https://github.com/cristiklein/puppet-developer-laptop.git
WORKDIR=/tmp/$USER/provision

set -e

if dpkg -s git &> /dev/null; then
	echo "Git already installed"
else
	echo "Installing git ..."
	sudo apt-get install -y git
fi

# setup git repo
if [ ! -d $WORKDIR ]; then
	mkdir -p $WORKDIR
	git clone $REPO_URL $WORKDIR
	cd $WORKDIR
else
	cd $WORKDIR
	git clean -fdx
	git pull
fi

./install.sh
