#!/bin/bash

REPO_URL=https://github.com/cristiklein/puppet-developer-laptop.git
WORKDIR=/tmp/$USER/provision

set -e

if dpkg -s git &> /dev/null; then
	echo "Git already installed"
else
	echo "Installing git ..."
	sudo apt-get install -y git
fi

# test for git-crypt
if dpkg -s git-crypt &> /dev/null; then
	echo "git-crypt already installed"
else
	echo "Installing git-crypt ..."
	sudo apt-get -y install git-crypt
fi

# setup git repo
if [ ! -d $WORKDIR ]; then
	mkdir -p $WORKDIR
	git clone --recursive $REPO_URL $WORKDIR
	cd $WORKDIR
else
	cd $WORKDIR
	git clean -fdx
	git pull
fi
git-crypt unlock

./install.sh
